Check if a sys_file could be found
Previously, if none of the things tried for sys_file exist, it remains
as None, which results in the rather unhelpful error message:

   Traceback (most recent call last):
     File "/test/dev_proc_sys.py", line 20, in <module>
       open(f, "rb").read(1)
   TypeError: expected str, bytes or os.PathLike object, not NoneType

Now we only try non-None paths, and emit a warning if sys_file is None

Signed-off-by: Matthew Vernon <mv3@sanger.ac.uk>